name: Build File-to-BIND Container and Push to a Remote Registry
on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/workflows/build-and-push.yml'
      - '.github/workflows/release.yml'
      - '.github/workflows/test.yml'
    branches:
      - main
  # Schedule workflow run at 00:00 on Sunday
  schedule:
    - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # Build the Container
  build-container:
    name: Build File-to-BIND Container
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:

    - name: Check out code
      uses: actions/checkout@v3.3.0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64,amd64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        # list of Docker images to use as base name for tags
        images: "${{ secrets.REGISTRY_REPO }}"
        # generate Docker tags based on the following events/attributes
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix=,suffix=,format=short
          type=sha,prefix=,suffix=,format=long
          type=raw,value=file-to-bind-latest

    - name: Login to Quay
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: "${{ secrets.REGISTRY_USERNAME }}"
        password: "${{ secrets.REGISTRY_TOKEN }}"

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        file: Containerfile.file-to-BIND
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64, linux/arm64
